version: '3.8'

services:
  gateway-service:
    extends:
      file: ./gateway-service/docker-compose.yaml
      service: gateway-service

  user-service:
    extends:
      file: ./user-service/docker-compose.yaml
      service: user-service

  user-service-db:
    extends:
      file: ./user-service/docker-compose.yaml
      service: user-service-db

  auth-service:
    extends:
      file: ./auth-service/docker-compose.yaml
      service: auth-service

  auth-service-db:
    extends:
      file: ./auth-service/docker-compose.yaml
      service: auth-service-db


  temporal-service:
    extends:
      file: ./temporal-service/docker-compose.yaml
      service: temporal-service

  temporal-service-db:
    extends:
      file: ./temporal-service/docker-compose.yaml
      service: temporal-service-db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"


  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 14268:14268
volumes:

  auth-db:

  user-db:

  temporal-db:

networks:
  default:
    name: microservices-network
