apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          ports:
            - containerPort: 5432
          image: postgres:15-alpine3.16
          env:
            - name: USER_SERVICE_PASSWORD
              value: "password"
            - name: USER_SERVICE_HOST
              value: "user-service-db"
            - name: USER_SERVICE_PORT
              value: "5432"
            - name: USER_SERVICE_USER
              value: "user_db"
            - name: USER_SERVICE_DB
              value: "user_db"
            - name: USER_SERVICE_DATABASE_URL
              value: "postgresql://${USER_SERVICE_USER}:${USER_SERVICE_PASSWORD}@${USER_SERVICE_HOST}:${USER_SERVICE_PORT}/${USER_SERVICE_DB}?schema=public"
