apiVersion: v1
kind: Service
metadata:
  name: temporal
  labels:
    app: temporal
spec:
  type: LoadBalancer
  selector:
    app: temporal
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
