name: Node.js CI

on:
  push:
    branches: [nhost_main, nhost_dev, main]
  pull_request:
    branches: [nhost_main, nhost_dev, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: ./frontend

      # - name: Run lint
      #   run: pnpm run lint
      #   working-directory: ./frontend

      - name: Build
        run: pnpm run build
        working-directory: ./frontend
